Baixe a imagem utilizando a tag: stable-slim, que é uma versão reduzida da distribuição.

docker pull debian:stable-slim

============================================================================

Após baixar a imagem para seu computador local, crie e execute um contêiner no modo interativo utilizando essa imagem como referência — não esqueça referenciar a tag.

docker container run -it debian:stable-slim 

==============================================================================

No terminal, você deve conseguir rodar o comando cat /etc/*-release, que vai retornar os dados da distribuição Debian que está sendo rodada dentro do contêiner.

docker container run -it debian:stableslim  
root@38218721cba4:/# cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

==============================================================================

Encerre o terminal.

exit

===============================================================================

Verifique na sua lista de contêiners qual contêiner se refere ao exercício que acabou de praticar.

docker container ls -a                                                                                          125 ↵
CONTAINER ID   IMAGE                COMMAND   CREATED          STATUS                          PORTS     NAMES
38218721cba4   debian:stable-slim   "bash"    6 minutes ago    Exited (0) About a minute ago             nostalgic_chaplygin
9d9ea1aa4228   debian:stable-slim   "bash"    37 minutes ago   Exited (0) 37 minutes ago                 romantic_elion

=================================================================================

Inicie o mesmo contêiner novamente, sem criar outro. Valide se ele está ativo na lista de contêiners.

docker container start nostalgic_chaplygin 
nostalgic_chaplygin

docker container ls -a
CONTAINER ID   IMAGE                COMMAND   CREATED          STATUS                      PORTS     NAMES
38218721cba4   debian:stable-slim   "bash"    9 minutes ago    Up 16 seconds                         nostalgic_chaplygin
9d9ea1aa4228   debian:stable-slim   "bash"    40 minutes ago   Exited (0) 39 minutes ago             romantic_elion

=====================================================================================

Retome o contêiner que foi criado anteriormente neste exercício. 

docker container exec -it nostalgic_chaplygin sh                                                                130 ↵
# |

=======================================================================================

Rode o comando cat /etc/debian_version que deve retornar a versão atual do sistema do contêiner.

docker container exec -it nostalgic_chaplygin sh                                                                130 ↵
# cat /etc/debian_version    
11.5
# |

========================================================================================

Encerre o terminal.

exit

==========================================================================================

Remova somente o contêiner criado para esse exercício.

docker container rm -f nostalgic_chaplygin      
nostalgic_chaplygin

docker container ls -a                                                                                          130 ↵
CONTAINER ID   IMAGE                COMMAND   CREATED          STATUS                      PORTS     NAMES
9d9ea1aa4228   debian:stable-slim   "bash"    56 minutes ago   Exited (0) 56 minutes ago             romantic_elion

